#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# 9 stages: 준비 → 광학 → 채널 설정 → 노출 4점 → 실내 조명 → 도출
TOTAL_STAGES=9

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTDIR="$ROOT/docs/measurements"
mkdir -p "$OUTDIR"
ENV_FILE="$OUTDIR/pwm-sweep.env"
REPORT="$OUTDIR/pwm-sweep-$(date +%Y-%m-%d).md"

# ripple MIN MAX — 리플 폭을 평균에 대한 백분율로. 비어 있거나 0이면 0.0.
ripple() {
  awk -v a="${1:-0}" -v b="${2:-0}" 'BEGIN{
    m=(a+b)/2
    if (m<=0) { printf "0.0"; exit }
    d=b-a; if (d<0) d=-d
    printf "%.1f", d/m*100
  }'
}

# point KEYBASE EXPOSURE_US EXPECTED_FPS — 노출을 바꾸고 15초 관찰해 min/max를 받는다.
point() {
  local base="$1" us="$2" fps="$3"
  local kmin="${base}_MIN" kmax="${base}_MAX"
  step "pane의 Settings → Exp 칸에 ${us} 를 입력하고 Apply 를 누릅니다."
  note "단위는 µs 입니다. ms 로 넣지 마십시오 (10 ms = 10000)."
  step "Apply 직후 Exp 칸에 ${us} 가 그대로 남아 있는지 확인합니다."
  note "상태줄 fps가 ≈ ${fps} 로 바뀌면 노출이 실제로 걸린 것입니다 — fps = 1/(노출+45µs)."
  warn "상태줄에 '⚠ missed' 가 보이면 중단하십시오. 유실이 섞이면 측정이 무의미합니다."
  warn "범례의 clip 이 0.0% 가 아니면 중단하십시오. 포화된 화면은 리플이 잘려 가짜 null을 만듭니다."
  say ""
  say "노출 변경 후 5초 기다린 다음, 하단 밝기 그래프 범례의 luma 숫자를 15초간 지켜봅니다."
  note "0.5초마다 갱신되므로 약 30개를 보게 됩니다. 리플이 없으면 값이 거의 고정됩니다."
  note "그래프 선도 같이 보십시오 — null 이면 선이 매끄럽고, 아니면 굵게 흔들립니다."
  pause "관찰이 끝나면 Enter"
  ask "$kmin" "그 15초의 최소 luma:"
  ask "$kmax" "그 15초의 최대 luma:"
  write_env "$kmin" "${!kmin}"
  write_env "$kmax" "${!kmax}"
  note "리플 $(ripple "${!kmin}" "${!kmax}")%"
  pause
}

banner "백라이트 PWM 주파수 측정 (노출 스윕)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "준비 — 앱을 정상 시작한 상태여야 합니다"
say "이 절차는 노출을 바꿔가며 밝기 리플이 사라지는 지점을 찾습니다."
say "리플이 0이 되는 노출은 PWM 주기의 정수배이므로, 거기서 주파수가 나옵니다."
say ""
warn "직전 실행을 작업 관리자나 디버거로 강제 종료했다면, 카메라의 일부 피처 쓰기가"
warn "조용히 거부됩니다. 그 상태에서는 노출이 안 바뀌는데 오류도 안 납니다."
step "앱이 떠 있으면 창을 정상적으로 닫고 (X 버튼) 다시 실행하십시오."
step "측정할 채널의 pane에서 '▶ Start' 를 눌러 grab 중인 것을 확인합니다."
step "'● Rec' 과 '◆ RAW' 가 모두 꺼져 있는지 확인합니다."
say ""
ask PWM_CHANNEL "측정할 채널 (pane 헤더의 CAM 번호, 예: CAM0):"
write_env PWM_CHANNEL "$PWM_CHANNEL"
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "광학 — 패널이 프레임을 채우고, 포화되지 않아야 합니다"
warn "분석 ROI는 아직 밝기 측정에 반영되지 않습니다 (오버레이만 그려집니다)."
warn "따라서 배경을 제외하는 일은 소프트웨어가 아니라 카메라 프레이밍으로 해야 합니다."
step "AVN 패널에 정지 화면을 띄웁니다 — 애니메이션, 영상, 지도 이동이 없어야 합니다."
note "콘텐츠가 움직이면 그 변화가 리플보다 커져서 측정이 불가능합니다."
step "패널이 화면(프레임)을 최대한 채우도록 카메라를 맞춥니다. 주변 배경을 최소화합니다."
step "범례의 luma 가 60~180 범위에 오도록 조리개 또는 패널 밝기를 맞춥니다."
step "범례의 clip 이 0.0% 인지 확인합니다."
note "포화(clip>0)된 화소는 리플이 255에서 잘려 없어집니다 — 가짜 null의 가장 흔한 원인입니다."
say ""
ask PWM_PANEL_BRIGHTNESS "패널 밝기 설정값 (예: 50% / 최대 / 불명):"
write_env PWM_PANEL_BRIGHTNESS "$PWM_PANEL_BRIGHTNESS"
note "패널을 어둡게 하면 PWM 듀티가 짧아져 리플이 커집니다. 어느 밝기에서 재는지가 기록에 남아야 합니다."
pause

# ── 3 ────────────────────────────────────────────────────────────────────
stage "채널 설정 — 자동 기능을 끄고, 측정 채널만 남깁니다"
step "Exp 옆의 'Auto' 체크를 해제합니다 (자동 노출이 켜져 있으면 스윕과 싸웁니다)."
step "WB 행의 'Auto' 체크를 해제합니다 (자동 화이트밸런스도 밝기를 움직입니다)."
step "Acq Rate 행의 'Limit' 체크를 해제합니다."
note "레이트 캡을 풀어 두면 노출만이 fps를 정하므로, fps로 노출 적용을 검증할 수 있습니다."
note "Decim 은 아무 값이나 괜찮습니다 — 이 측정에 영향이 없습니다."
note "예전에는 decim 2를 요구했습니다. 천장이 1.7 GB/s이던 시절 단일 채널 원본 해상도가"
note "200 fps에서 그것을 넘었기 때문입니다. 2026-08-27에 보드를 x16 슬롯으로 옮겨 천장이"
note "3.68 GB/s가 되면서 그 이유가 없어졌습니다 (원본 1채널 198 fps = 1.89 GB/s)."
step "다른 채널들은 '■ Stop' 으로 정지시킵니다. 측정 채널만 grab 상태로 둡니다."
note "채널이 여러 개면 천장 근처에서 배분이 불공정해져 유실이 섞입니다."
say ""
ask PWM_ROOM_LIGHT "현재 실내 조명 상태 (켜짐 / 꺼짐 / 조광):"
write_env PWM_ROOM_LIGHT "$PWM_ROOM_LIGHT"
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "기준점 — 노출 6500 µs (어느 PWM도 소거하지 않는 값)"
say "먼저 '리플이 있는 상태'가 어떻게 보이는지 기준을 잡습니다."
note "6500 µs 는 153.8 Hz의 정수배 지점이라, 흔한 PWM 주파수(200·240·480·1000 Hz)를"
note "어느 것도 소거하지 않습니다. 여기서 나온 값이 비교 기준이 됩니다."
say ""
point PWM_6500 6500 152.8

# ── 5 ────────────────────────────────────────────────────────────────────
stage "스윕 1/3 — 노출 5000 µs (100 Hz 계열 시험)"
note "5.000 ms 는 200 Hz·1000 Hz 등 100 Hz의 배수를 정확히 소거합니다."
say ""
point PWM_5000 5000 198.2

# ── 6 ────────────────────────────────────────────────────────────────────
stage "스윕 2/3 — 노출 8333 µs (120 Hz 계열 시험)"
note "8.333 ms 는 120·240·480·960 Hz 를 정확히 소거합니다."
note "이 값이 최소로 나오면 실내 조명 리플(국내 120 Hz)까지 함께 죽는 유리한 경우입니다."
say ""
point PWM_8333 8333 119.4

# ── 7 ────────────────────────────────────────────────────────────────────
stage "스윕 3/3 — 노출 10000 µs (100 Hz 계열 확인)"
note "10.000 ms 도 100 Hz의 배수를 소거합니다. 5000 µs 와 함께 낮게 나오면"
note "100 Hz 계열이라는 판정이 두 점으로 확인됩니다."
say ""
point PWM_10000 10000 99.6

# ── 8 ────────────────────────────────────────────────────────────────────
stage "실내 조명 단독 — 패널을 끄고 반사광만 봅니다"
say "여기서 재는 것은 패널이 아니라 방입니다. 실내 조명이 반사광으로 측정에 섞여"
say "들어오는지, 그리고 그것이 120 Hz인지 확인합니다."
step "AVN 패널의 전원을 끕니다. 카메라는 같은 위치에 그대로 둡니다."
note "렌즈를 가리지 마십시오 — 그러면 조명이 아니라 센서 암전류를 재게 됩니다."
step "패널 표면의 반사광으로 luma 가 20 이상 나오는지 확인합니다."
note "너무 어두우면 조리개를 열거나, 이 단계를 건너뛰고 도출 단계에서 0 으로 두십시오."
say ""
say "먼저 6500 µs (기준):"
point ROOM_6500 6500 152.8
say "이어서 8333 µs (120 Hz 소거 지점):"
point ROOM_8333 8333 119.4
step "패널 전원을 다시 켭니다."
pause

# ── 9 ────────────────────────────────────────────────────────────────────
stage "도출 — 권장 노출과 취득 fps"

R_REF=$(ripple "$PWM_6500_MIN" "$PWM_6500_MAX")
R_5000=$(ripple "$PWM_5000_MIN" "$PWM_5000_MAX")
R_8333=$(ripple "$PWM_8333_MIN" "$PWM_8333_MAX")
R_10000=$(ripple "$PWM_10000_MIN" "$PWM_10000_MAX")
R_ROOM_REF=$(ripple "$ROOM_6500_MIN" "$ROOM_6500_MAX")
R_ROOM_8333=$(ripple "$ROOM_8333_MIN" "$ROOM_8333_MAX")

say "노출별 리플"
printf '    %-12s %8s\n' "6500 µs" "${R_REF}%"
printf '    %-12s %8s   %s\n' "5000 µs" "${R_5000}%" "(100 Hz 계열)"
printf '    %-12s %8s   %s\n' "8333 µs" "${R_8333}%" "(120 Hz 계열)"
printf '    %-12s %8s   %s\n' "10000 µs" "${R_10000}%" "(100 Hz 계열)"
say ""
say "실내 조명 단독"
printf '    %-12s %8s\n' "6500 µs" "${R_ROOM_REF}%"
printf '    %-12s %8s\n' "8333 µs" "${R_ROOM_8333}%"
say ""

VERDICT=$(awk -v ref="$R_REF" -v a="$R_5000" -v b="$R_8333" -v c="$R_10000" 'BEGIN{
  if (ref < 1.0) { print "NOREF"; exit }
  lim = ref/3
  best="F100"; bv=a
  if (c < bv) bv=c
  if (b < bv) { bv=b; best="F120" }
  if (bv > lim) best="NONE"
  print best
}')

case "$VERDICT" in
  F120)
    EXPOSURE_US=8333; TARGET_FPS=120
    say "판정: PWM 주파수는 120 Hz의 배수입니다 (240 · 480 · 960 Hz 중 하나)."
    say "권장 노출 8333 µs, 취득 fps 120."
    note "실내 조명 리플(120 Hz)도 같은 노출에서 함께 소거되는 유리한 경우입니다."
    ;;
  F100)
    EXPOSURE_US=10000; TARGET_FPS=100
    say "판정: PWM 주파수는 100 Hz의 배수입니다 (200 · 1000 Hz 중 하나)."
    say "권장 노출 10000 µs, 취득 fps 100."
    note "5000 µs 도 같은 계열을 소거하지만, 10000 µs 가 검출 하한 1.0 ms 로 더 여유롭습니다."
    warn "이 노출은 실내 조명 120 Hz 를 소거하지 못합니다 — 아래 조명 항목을 확인하십시오."
    ;;
  NONE)
    EXPOSURE_US=8333; TARGET_FPS=120
    say "판정: 시험한 어느 노출에서도 리플이 충분히 떨어지지 않았습니다."
    say "PWM 주파수가 100·120 Hz 계열이 아니거나, 이 패널이 DC 조광일 수 있습니다."
    note "다음 단계: 노출을 4000~11000 µs 사이에서 250 µs 간격으로 훑어 최소점을 직접 찾으십시오."
    note "최소점 T 에서 주파수는 f = k/T (k = 1, 2, 3...) 중 하나입니다."
    warn "임시 권장은 8333 µs / 120 fps 입니다 — 실내 조명 120 Hz 는 최소한 소거됩니다."
    ;;
  NOREF)
    EXPOSURE_US=8333; TARGET_FPS=120
    say "판정: 기준점(6500 µs)에서도 리플이 거의 없었습니다."
    say "이 패널에 PWM 조광이 없거나(DC 조광), 화면이 포화되어 리플이 잘렸을 수 있습니다."
    warn "범례의 clip 이 0.0% 였는지 다시 확인하십시오. 포화는 가짜 null 의 주범입니다."
    note "PWM 이 정말 없다면 노출은 PWM 이 아니라 감도로 정하면 됩니다 — 짧은 노출이 유리합니다."
    ;;
esac

write_env PWM_VERDICT "$VERDICT"
write_env PWM_EXPOSURE_US "$EXPOSURE_US"
write_env PWM_TARGET_FPS "$TARGET_FPS"

say ""
ROOM_NOTE=$(awk -v r="$R_ROOM_REF" -v n="$R_ROOM_8333" 'BEGIN{
  if (r < 1.0) { print "실내 조명 리플은 검출되지 않았습니다 — 차광이 필요하지 않습니다."; exit }
  if (n < r/3) { print "실내 조명 리플이 8333 µs 에서 소거되었습니다 — 120 Hz 로 확인됩니다."; exit }
  print "실내 조명 리플이 있고 8333 µs 에서도 남습니다 — 120 Hz 가 아닙니다. 차광이 필요합니다."
}')
say "$ROOM_NOTE"

cat > "$REPORT" <<REPORT_EOF
# 백라이트 PWM 노출 스윕 측정

측정일: $(date +%Y-%m-%d)
채널: ${PWM_CHANNEL}
패널 밝기: ${PWM_PANEL_BRIGHTNESS}
실내 조명: ${PWM_ROOM_LIGHT}
설정: Decim 2, 자동 노출 OFF, 자동 WB OFF, Acq Rate Limit OFF, 측정 채널만 grab

## 패널 (정지 화면)

| 노출 | 소거 대상 | 최소 luma | 최대 luma | 리플 |
|---|---|---|---|---|
| 6500 µs | 없음 (기준) | ${PWM_6500_MIN} | ${PWM_6500_MAX} | ${R_REF}% |
| 5000 µs | 100 Hz 계열 | ${PWM_5000_MIN} | ${PWM_5000_MAX} | ${R_5000}% |
| 8333 µs | 120 Hz 계열 | ${PWM_8333_MIN} | ${PWM_8333_MAX} | ${R_8333}% |
| 10000 µs | 100 Hz 계열 | ${PWM_10000_MIN} | ${PWM_10000_MAX} | ${R_10000}% |

## 실내 조명 단독 (패널 OFF)

| 노출 | 최소 luma | 최대 luma | 리플 |
|---|---|---|---|
| 6500 µs | ${ROOM_6500_MIN} | ${ROOM_6500_MAX} | ${R_ROOM_REF}% |
| 8333 µs | ${ROOM_8333_MIN} | ${ROOM_8333_MAX} | ${R_ROOM_8333}% |

## 판정

- 코드: \`${VERDICT}\`
- **권장 노출: ${EXPOSURE_US} µs**
- **권장 취득 fps: ${TARGET_FPS}**
- 실내 조명: ${ROOM_NOTE}

## 근거

노출 T 의 박스 적분은 주파수 f 성분을 \`|sinc(pi*f*T)|\` 배로 통과시키고, \`f*T\` 가 정수이면
정확히 0 이다. 따라서 리플이 최소가 되는 노출은 PWM 주기의 정수배이며, 거기서 주파수 계열이
역산된다. 리플 자체는 500 ms 틱이 매번 한 프레임을 무작위 위상으로 표본화하기 때문에
관측되는 luma 산포로 나타난다 — 파형이 아니라 진폭만 보는 방법이다.

## 반영할 곳

- \`research.md\` 8절 실측표에 이 표를 추가
- \`docs/superpowers/specs/2026-08-20-avn-anomaly-detection-design.md\` 2절의 노출·fps 표를
  이 값으로 확정 (현재는 100 fps 가정)
- 앱 설정: 채널마다 노출 ${EXPOSURE_US} µs, Acq Rate Limit ON + ${TARGET_FPS} fps
REPORT_EOF

say ""
note "보고서: $REPORT"
note "원시 값: $ENV_FILE (재실행하면 Enter 로 이전 값을 유지합니다)"
say ""
warn "Acq Rate 를 ${TARGET_FPS} 로 걸어 두면 그 값은 카메라에 영속됩니다."
warn "앱을 닫아도 남으므로, 다른 목적으로 쓸 때는 되돌려야 합니다."
pause

finish
