#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the app takes the readings; this drives it and checks the physical setup.
#
# It used to ask a person to watch a luma number for fifteen seconds and type the smallest and
# largest they saw, six times over. That was the least reliable part of the measurement, and the
# only part a machine does better: `--pwm-sweep` takes hundreds of readings per exposure instead
# of thirty and cannot mis-read one. What is left here is what only a person can do — put a still
# picture on the panel, aim the camera, draw the ROI, and set the aperture.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXE="$ROOT/src/bin/x64/Release/net10.0-windows/MatroxFrameGrabber.exe"
OUTDIR="$(dirname "$EXE")/measurements"
ENV_FILE="$ROOT/docs/measurements/pwm-sweep.env"
mkdir -p "$(dirname "$ENV_FILE")"

# run_sweep LABEL ARGS... — run the app unattended and wait. It closes itself.
run_sweep() {
  local label="$1"; shift
  if [[ ! -x "$EXE" && ! -f "$EXE" ]]; then
    warn "실행 파일이 없습니다: $EXE"
    warn "먼저 빌드하십시오: dotnet build MatroxFrameGrabber.slnx -c Release"
    return 1
  fi
  printf '  %s▶ 측정 중%s %s — 약 %s초, 창이 스스로 닫힙니다.\n' \
    "$GREEN" "$RESET" "$label" "$2"
  note "이 동안 패널과 카메라를 건드리지 마십시오."
  "$EXE" "${@:3}" || true
  printf '  %s✓%s %s 완료\n' "$GREEN" "$RESET" "$label"
}

banner "백라이트 PWM 주파수 측정 (노출 스윕)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "준비 — 앱이 정상 종료된 상태여야 합니다"
say "노출을 바꿔가며 밝기 리플이 사라지는 지점을 찾습니다."
say "리플이 0이 되는 노출은 PWM 주기의 정수배이므로, 거기서 주파수가 나옵니다."
say ""
warn "직전 실행을 작업 관리자나 디버거로 강제 종료했다면, 카메라의 일부 피처 쓰기가"
warn "조용히 거부됩니다. 그 상태에서는 노출이 안 바뀌는데 오류도 안 납니다."
step "앱이 떠 있으면 창을 정상적으로 닫으십시오 (X 버튼). 스윕이 직접 다시 띄웁니다."
say ""
ask PWM_CHANNEL "측정할 채널 (예: CAM0 또는 0):"
write_env PWM_CHANNEL "$PWM_CHANNEL"
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "광학 — ROI가 패널만 덮고, 포화되지 않아야 합니다"
say "밝기는 분석 ROI 안에서만 측정됩니다. ROI를 그리지 않으면 화면 전체가 대상입니다."
say "이 단계는 앱을 직접 열어서 눈으로 맞춰야 합니다."
say ""
step "AVN 패널에 정지 화면을 띄웁니다 — 애니메이션, 영상, 지도 이동이 없어야 합니다."
note "콘텐츠가 움직이면 그 변화가 리플보다 커져서 측정이 불가능합니다."
step "패널 화면 안쪽에 ROI 사각형을 드래그해 그립니다. 베젤과 배경이 들어가지 않게 합니다."
note "가장자리를 조금 안쪽으로 잡으십시오. 베젤 경계는 반사광이 강해 값을 흔듭니다."
step "범례의 luma 가 60~180 범위에 오도록 조리개 또는 패널 밝기를 맞춥니다."
step "범례의 clip 이 0.0% 인지 확인합니다."
note "포화된 화소는 리플이 255에서 잘려 없어집니다 — 가짜 null의 가장 흔한 원인입니다."
note "스윕이 clip 을 기록해서, 포화됐으면 보고서가 판정을 신뢰할 수 없다고 표시합니다."
say ""
ask PWM_PANEL_BRIGHTNESS "패널 밝기 설정값 (예: 50% / 최대 / 불명):"
write_env PWM_PANEL_BRIGHTNESS "$PWM_PANEL_BRIGHTNESS"
note "패널을 어둡게 하면 PWM 듀티가 짧아져 리플이 커집니다. 어느 밝기인지가 기록에 남아야 합니다."
pause

# ── 3 ────────────────────────────────────────────────────────────────────
stage "채널 설정 — 자동 기능을 끄고, 측정 채널만 남깁니다"
step "Exp 옆의 'Auto' 체크를 해제합니다 (자동 노출이 스윕과 싸웁니다)."
step "WB 행의 'Auto' 체크를 해제합니다 (자동 화이트밸런스도 밝기를 움직입니다)."
step "Acq Rate 행의 'Limit' 체크를 해제합니다."
note "레이트 캡을 풀어야 노출만이 fps를 정합니다 — 그래야 노출이 실제로 걸렸는지 fps로 확인됩니다."
note "Decim 은 아무 값이나 괜찮습니다 — 이 측정에 영향이 없습니다."
step "다른 채널들은 '■ Stop' 으로 정지시킵니다."
note "채널이 여러 개면 천장 근처에서 배분이 불공정해져 유실이 섞입니다."
say ""
ask PWM_ROOM_LIGHT "현재 실내 조명 상태 (켜짐 / 꺼짐 / 조광):"
write_env PWM_ROOM_LIGHT "$PWM_ROOM_LIGHT"
step "이제 앱을 정상 종료하십시오 (X 버튼). 설정은 저장되고, 스윕이 다시 띄웁니다."
pause "앱을 닫았으면 Enter"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "패널 측정 — 노출 4점, 자동"
say "6500 µs (기준) · 5000 · 8333 · 10000 을 차례로 걸고 각각 15초씩 수집합니다."
note "6500 은 흔한 PWM 주파수를 어느 것도 소거하지 않아 '리플이 있는 상태'의 기준이 됩니다."
note "5000·10000 은 100 Hz 계열을, 8333 은 120 Hz 계열을 소거합니다."
say ""
run_sweep "패널" 80 --pwm-sweep "$PWM_CHANNEL"
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "실내 조명 단독 — 패널을 끄고 반사광만 봅니다"
say "여기서 재는 것은 패널이 아니라 방입니다. 실내 조명이 반사광으로 섞여 들어오는지,"
say "그리고 그것이 120 Hz(국내 전기)인지 확인합니다."
say ""
step "AVN 패널의 전원을 끕니다. 카메라는 같은 위치에 그대로 둡니다."
warn "렌즈를 가리지 마십시오 — 그러면 조명이 아니라 센서 암전류를 재게 됩니다."
note "너무 어두워 luma 가 20 아래면 이 단계는 건너뛰어도 됩니다 (보고서가 '측정 안 함'으로 적습니다)."
say ""
if confirm "패널을 껐습니다. 실내 조명을 측정할까요?"; then
  run_sweep "실내 조명" 40 --pwm-sweep "$PWM_CHANNEL" --pwm-room
  step "패널 전원을 다시 켭니다."
else
  note "건너뜁니다."
fi
pause

# ── 6 ────────────────────────────────────────────────────────────────────
stage "결과"
REPORT="$OUTDIR/pwm-sweep-$(date +%Y-%m-%d).md"
if [[ -f "$REPORT" ]]; then
  sed -n '/^## 판정/,/^## 근거/p' "$REPORT" | sed '$d' | sed 's/^/  /'
  say ""
  note "보고서 : $REPORT"
  note "원시값 : $OUTDIR/pwm-sweep.csv"
else
  warn "보고서가 없습니다. 스윕이 실패했을 수 있습니다."
  note "로그를 보십시오: %LOCALAPPDATA%\MatroxFrameGrabber\mil-errors.log  ('pwm-sweep:' 줄)"
fi
say ""
say "다음에 할 것:"
step "권장 노출을 세 채널 모두에 동일하게 넣습니다 (fps가 균등해야 검출 하한이 같아집니다)."
step "research.md 8절과 설계 스펙 2절의 노출·fps 표를 이 값으로 확정합니다."
pause

finish
